clear;
clf;
dt = 1;
t = -5 : dt : 5;
x = t.*t;
subplot(211);
plot(t, x);
xgrid(1);
xlabel("t", "fontsize", 4);
ylabel("x", "fontsize", 4);
title("Parabola x = t^2", "fontsize", 4);
// x = sqrt(t^2 - 1);
x = 1./t;
subplot(212);
plot(t, x);
xgrid(1);
xlabel("t", "fontsize", 4);
ylabel("x", "fontsize", 4);
title("Hyperbola xt = 1", "fontsize", 4);